CREATE TABLE IF NOT EXISTS guests (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  max_passes INTEGER NOT NULL DEFAULT 1 CHECK (max_passes BETWEEN 1 AND 20),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rsvps (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  guest_id BIGINT NOT NULL UNIQUE REFERENCES guests(id) ON DELETE CASCADE,
  attending BOOLEAN NOT NULL,
  guests_count INTEGER NOT NULL DEFAULT 0 CHECK (guests_count BETWEEN 0 AND 20),
  message TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS check_ins (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  guest_id BIGINT NOT NULL UNIQUE REFERENCES guests(id) ON DELETE CASCADE,
  scanned_by TEXT NOT NULL,
  checked_in_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS album_photos (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  guest_id BIGINT NOT NULL REFERENCES guests(id) ON DELETE CASCADE,
  object_key TEXT NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  content_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'approved',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_album_photos_status_created_at
  ON album_photos(status, created_at DESC);

INSERT INTO guests (token, name, max_passes)
VALUES ('familia-castro-cuevas', 'Familia Castro Cuevas', 4)
ON CONFLICT (token) DO NOTHING;
